# Generated by Django 6.0.3 on 2026-03-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="slug",
            field=models.SlugField(default="slug-default", unique=True),
            preserve_default=False,
        ),
    ]
