# Generated by Django 6.0.3 on 2026-03-10 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="knowledge_base.category",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["title"], name="knowledge_b_title_4801c7_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["slug"], name="knowledge_b_slug_c37eab_idx"),
        ),
    ]
