# Generated by Django 6.0.3 on 2026-03-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="logevent",
            index=models.Index(
                fields=["timestamp"], name="logs_analys_timesta_bd2f39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="logevent",
            index=models.Index(
                fields=["event_type"], name="logs_analys_event_t_aa28bc_idx"
            ),
        ),
    ]
