# Generated by Django 6.0.3 on 2026-03-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('official_site', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('difficulty', models.CharField(max_length=50)),
            ],
        ),
    ]
