# Generated by Django 6.0.3 on 2026-03-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attack_lab", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lab",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                max_length=10,
            ),
        ),
    ]
