# Generated by Django 6.0.3 on 2026-03-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attack_lab", "0002_alter_lab_difficulty"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
