# Generated by Django 6.0.3 on 2026-03-10 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="roadmapstep",
            unique_together={("roadmap", "order")},
        ),
    ]
