# Generated by Django 6.0.3 on 2026-03-14 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0002_alter_roadmapstep_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roadmapstep",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="roadmap",
            name="slug",
            field=models.SlugField(default="None", unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="roadmapstep",
            name="roadmap",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="roadmap.roadmap",
            ),
        ),
    ]
