# Generated by Django 6.0.3 on 2026-03-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0003_alter_roadmapstep_options_roadmap_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmapstep",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
