# Generated by Django 6.0.3 on 2026-03-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0004_roadmapstep_slug"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="roadmapstep",
            unique_together={("roadmap", "order"), ("roadmap", "slug")},
        ),
    ]
