# Generated by Django 6.0.3 on 2026-03-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0005_alter_roadmapstep_unique_together"),
        ("security_tools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmapstep",
            name="tools",
            field=models.ManyToManyField(
                blank=True, related_name="steps", to="security_tools.securitytool"
            ),
        ),
    ]
